### ISSUE TITLE
MSC-2020 Updated List Tracker

### ISSUE THREAD

**Issue by paragbhatt** [epicfaace/CFF#128]
- [x] Add the family ID 
- [ ] Change the page look based on PDF sent by Shailaja Sharma. 
- [ ] On the Confirmation page, for Check payments, please add a note at the top and bottom, saying "Your registration is not complete until you click 'Pay by Check' "
- [ ] - On the success page for check by installment, the bullet points needs to be put in table.  Parag has issue centering table.
- [x] For installment payments, change date format to "August 04, 2019" instead of 08-19-2019
- [ ] -
- [ ] -

**Comment by epicfaace** [comment]
Superseded by #141
